name: GitHub Actions
on:
  push: 
    branches: [master, main]
  pull_request:
    branches: [master, main, develop]  
  workflow_dispatch:
  
jobs:
  Job-1:
   runs-on: Ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Hello GitHub
       run: echo "Hello Git Hub Actions"
       shell: bash
  Job-2:
   runs-on: Ubuntu-latest
   steps:
     - name: Bye GitHub
       run: echo "Good Bye...!!!"
       shell: bash
     
